name: Push Dev Container

on:
  workflow_dispatch:
  push:
    paths:
      - ./**
    branches: ["main"]
  pull_request:
    paths:
      - ./**
    branches: ["main"]

jobs:
  build-dev-containers:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image:
          [
            "manylinux2014_x86_64",
            "manylinux2014_aarch64",
            "manylinux_2_28_x86_64",
            "manylinux_2_28_aarch64",
          ]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./${{ matrix.image }}/Dockerfile
          push: true
          tags: congyuwang/${{ matrix.image }}:llvm-19.1.3
          cache-from: type=registry,ref=congyuwang/${{ matrix.image }}:llvm-19.1.3
          cache-to: type=inline
